### ISSUE TITLE
Don't show the start button

### ISSUE THREAD

**Issue by amir-gharajedaghi** [iamrohitsuthar/Quizller#11]
![Capture](https://user-images.githubusercontent.com/25272061/79081174-23c16300-7d30-11ea-9d61-d796bd8fd218.PNG)

**Comment by iamrohitsuthar** [comment]
Make sure the test is in Running Mode.
You can check the status of the test in the details section of test

**Comment by amir-gharajedaghi** [comment]
1. Yes, the test is running mode.
2. I'm login in with any password and user when generating user and password.
the problem does not show the start test button.
![Capture](https://user-images.githubusercontent.com/25272061/79284384-b77d6580-7ecf-11ea-8a95-5ecfb163cc23.PNG)
![03](https://user-images.githubusercontent.com/25272061/79284391-c106cd80-7ecf-11ea-843d-5d151e54e725.PNG)
![66](https://user-images.githubusercontent.com/25272061/79284552-3d99ac00-7ed0-11ea-855b-5f708748f846.PNG)

**Comment by ashawe** [comment]
@amir-gharajedaghi Can you turn on errors on your PHP and see if anything is there?
Also, guide us through how you got this error

**Comment by rajking16** [comment]
remove these line of code from dashboard.php and it will definetly gonna work....

session_start();
    
     if($_SESSION['test_ongoing']  == "true"){
       echo "Test Ongoing";
        header("Location: quiz.php");
     }
    else if(!isset($_SESSION['student_details'])){
        echo "You are not logged in";
        header("Location: ../index.php");
    }
