### ISSUE TITLE
Spreadsheet file format

### ISSUE THREAD

**Issue by ashawe** [iamrohitsuthar/Quizller#13]
We can also add questions via a csv file.
There is not mentioned what should the columns be.
Should they be in the following order? If so, comment and I'll make the changes so that the site mentions this
Question
Option A
Option B
Option C
Option D
Correct Option
Score

**Comment by iamrohitsuthar** [comment]
Yes, the file should contain the columns in the above order only. 
You can mention the information regarding this in the readme and also it would be great if you provide one sample questions file for reference purposes so that it will be useful in the testing.

**Comment by ashawe** [comment]
Sure! The I would like to take this issue
