### ISSUE TITLE
Run Quizller

### ISSUE THREAD

**Issue by ArbillIT** [iamrohitsuthar/Quizller#16]
How can i Run the quizller? I already put the folder of quizller to my xampp folder, and import the script.. please need your help. Thanks so much

**Comment by iamrohitsuthar** [comment]
Access the folder from the browser
like localhost://you_folder_path
By default Student login will open i.e. index.html from the root folder and for admin access go to /admin path.

**Comment by iamrohitsuthar** [comment]
Are you still facing the problem or issue is resolved?
