### ISSUE TITLE
Help me to login

### ISSUE THREAD

**Issue by abhisheksuna333** [iamrohitsuthar/Quizller#17]
You have created a great online quiz system with pro feature. Thanks for uploading such valuable code. I am a new php learner so , i am not able to login to admin page after entering username:- admin and password:- nimda / sha256. I also tried tried many password by decrypting the password code. 

I am running the file in localhost ( root, blank password, databasename:- sampleData )

What changes i need to do here:-

<?php
//database configurations
define("DB_HOST","localhost");
define("DB_UNAME","YOUR_DATABASE_USER_NAME");
define("DB_PASS","YOUR_DATABASE_PASSWORD");
define("DB_DNAME","YOUR_DATABASE_NAME");
$conn=mysqli_connect(DB_HOST,DB_UNAME,DB_PASS,DB_DNAME);
?>

**Comment by iamrohitsuthar** [comment]
Have you imported the sample data file on the database?

**Comment by abhisheksuna333** [comment]
Yes, sir i have imported the data in my localhost phpmyadmin.. and set the database name as sampleData.sql as mentioned in the database folder...the import was success...

**Comment by iamrohitsuthar** [comment]
Okay, so have you changed the db config file accoding to your configuration?

**Comment by abhisheksuna333** [comment]
<?php
//database configurations
define("DB_HOST","localhost");
define("DB_UNAME","YOUR_DATABASE_USER_NAME");
define("DB_PASS","YOUR_DATABASE_PASSWORD");
define("DB_DNAME","YOUR_DATABASE_NAME");
$conn=mysqli_connect(DB_HOST,DB_UNAME,DB_PASS,DB_DNAME);
?>

My database imported name is :- sampleData.sql
Host is :- localhost
username:- root
password:- ( blank )


What changes i need to do here i am not able to know... While changing YOU_DATABASE_USER_NAME to root.  It is not working... Help me to find my mistake sir..

**Comment by iamrohitsuthar** [comment]
Go to the database/config.php file and add an echo statement by checking the connection object in the if construct and execute the config file directly and check whether there is any problem in the connection establishment or not.
