### ISSUE TITLE
I have one question

### ISSUE THREAD

**Issue by speedspino21** [iamrohitsuthar/Quizller#24]
How to give roll number? it says invalid roll number.
I need this kind of project to be done, if you dont mind, kindly feel free to chat with me

**Comment by iamrohitsuthar** [comment]
can you please share the details with the screenshots?

**Comment by SergeyK27** [comment]
Do you have skype? If you have share with me.

**Comment by SergeyK27** [comment]
Do you have skype? or telegram?

**Comment by SergeyK27** [comment]
I want to hire you with quiz app project as you have skills.
My skype is live:starmonitor, you can ping me, thanks.

**Comment by SergeyK27** [comment]
I am waiting.

**Comment by SergeyK27** [comment]
http://prntscr.com/103cgz0, I tried to login with thin info.
But the result is like this.
http://prntscr.com/103cjiu
Kindly let me know reason,

**Comment by oureco123** [comment]
It's because there's no test running

**Comment by iamrohitsuthar** [comment]
Invalid roll number issue has been fixed. Please feel free to reopen it if necessary.
