### ISSUE TITLE
popper.js error

### ISSUE THREAD

**Issue by copperkam** [iamrohitsuthar/Quizller#34]
Howdy, I was going to test this software out on an IFASTNET premium server, so that itself may be the issue lol.

So whenever i try to log in using the admin login from the sample database set, i get several error 404s for the css of the page, but then the big error is  "caught Error: Bootstrap dropdown require Popper.js (https://popper.js.org)"

I'm still fairly new to JS, PHP, and all that further jazz, so if it's an easy fix, oops. 

Otherwise, thank you for your time 👍

**Comment by copperkam** [comment]
Actually there is now a second error that appears claiming "error 404 vendor/select2/select2.min.css not found" However, I don't see this anywhere here even? maybe this relates to popper somehow, my lack of knowledge on it is kind of keeping me at a standstill from using this. I'm going to try a fresh install and see if I just goofed it up while uploading it to my server.

**Comment by iamrohitsuthar** [comment]
This issue has been resolved and is now closed. Please feel free to reopen it if necessary.

**Comment by murat-ti** [comment]
Just add the following line:
`<script src="vendor/bootstrap/js/popper.min.js"></script>`
before
`<script src="vendor/bootstrap/js/bootstrap.min.js"></script>`

The final result should be:
`...`
`<script src="vendor/bootstrap/js/popper.min.js"></script>`
`<script src="vendor/bootstrap/js/bootstrap.min.js"></script>`
`...`
