### ISSUE TITLE
Exe file

### ISSUE THREAD

**Issue by malikabhishek2295** [iamrohitsuthar/Quizller#8]
Hi,
I make this project's exe file with the help of phpdesktop chrome and inno setup, which is working good on desktop, but when i run exe file in laptop it is showing error of Dll file missing. I downloaded these files but still issue occurs, please help me.

Email: abhishekmalik432@gmail.com

**Comment by iamrohitsuthar** [comment]
Share more info about the error.

**Comment by malikabhishek2295** [comment]
Whenever  I am trying to send exe file in my laptop & run this. It will always show an error that you have  the dll files missing .

**Comment by sgsourabh30** [comment]
@malikabhishek2295 The dll related errors o cur mostly due to missing drivers. Please ensure that all your drivers are updated.
